# Name of the workflow
name: Build and Push Docker Image

# Trigger the workflow on a push event to the main or dev branch
on:
  push:
    branches:
      - main
      - dev

# Define a job to build and push the Docker image
jobs:
  build-and-push:
    # Use the latest Ubuntu image as the build environment
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub and ghcr using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored as a secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password stored as a secret

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image and tag it with the git commit hash and ghcr.io registry
      - name: Build and tag Docker image
        run: |
          # Build the Docker image and tag it with the git commit hash
          docker build -t patrickgoulding/flexport-takehome:${{ github.sha }} .

          # Tag the Docker image for the ghcr.io registry
          docker tag patrickgoulding/flexport-takehome:${{ github.sha }} ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}

      # Step 4: Push the Docker image to the registry
      - name: Push Docker image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            patrickgoulding/flexport-takehome:${{ github.sha }}
            ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}
          # Pass in Docker Hub credentials as environment variables
