# Name of the workflow
name: Build and Push Docker Image

# Trigger the workflow on a push event to the main branch
on:
  push:
    branches:
      - main
      - dev

# Define a job to build and push the Docker image
jobs:
  build-and-push:
    # Use the latest Ubuntu image as the build environment
    runs-on: ubuntu-latest

    # Define the steps for the job
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub and ghcr using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username stored as a secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password stored as a secret

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image and tag it with the git commit hash and ghcr.io registry
      - name: Build and tag Docker image
        run: |
          # Build the Docker image and tag it with the git commit hash
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} .

          # Tag the Docker image for the ghcr.io registry
          docker tag ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }}

      # Step 4: Test the Docker image by running it and checking for a response of "OK"
      - name: Test Docker image
        run: |
          # Run the Docker image and map port 5000
          docker run -d -p 5000:5000 --name rockpaperscissorsapp ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

          # Wait for the app to start
          sleep 5

          # Make a request to the app and check for a response of "OK"
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://127.0.0.1:5000/health)
          if [ $response -ne 200 ]; then
            echo "Error: health check failed"
            exit 1
          fi

          # Stop the Docker container
          docker stop rockpaperscissorsapp

      # Step 5: Push the Docker image to the registry
      - name: Push Docker image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} # Docker Hub image tag
            ghcr.io/${{ github.actor }}/${{ github.repository }}:${{ github.sha }} # ghcr.io registry image tag
          # Pass in Docker Hub credentials as environment variables
